### ISSUE TITLE
StrEnum support (python 3.11)

### ISSUE THREAD

**Issue by zifeo** [zifeo/dataconf#89]
See discussion in #88

**Comment by bakobako** [comment]
@zifeo The solution in [#88](https://github.com/zifeo/dataconf/pull/88) does actually support the StrEnum. I tried to [add a test to the test_parse](https://github.com/zifeo/dataconf/pull/91) to show this, but since StrEnum is only added in 3.11, all tests for Python versions 3.8-3.10 are failing, since StrEnum cannot be imported.

**Comment by zifeo** [comment]
Released in version 2.2.0.
